### ISSUE TITLE
Unable to validate the snippets, snippets not working

### ISSUE THREAD

**Issue by sga11** [estin/simple-completion-language-server#43]
I am unable to get snippets to work, word auto-completion works correctly, and i am also able to get other LSPs also working, i am testing in a LaTeX file, i checked the other issues, but i think this is different because validation failed

i have tried to almost copy exactly from readme

my helix config.toml is almost blank
`theme = "sg_black"

[editor]
# line-number = "relative"
scroll-lines = 5
cursorline = true
auto-save = true
idle-timeout = 30000
gutters = ["diagnostics", "diff"]

[editor.soft-wrap]
enable = true
wrap-indicator = ""
`
and my languages.toml
`use-grammars = { only = [ "rust", "markdown", "python", "java", "c", "cpp", "latex", "bibtex", "json", "toml", "html" ] }
[language-server.texlab.config.texlab.build]
onSave = true
forwardSearchAfter = true

[language-server.texlab.config.texlab.forwardSearch]
executable = "zathura"
args = [ "--synctex-forward", "%l:1:%f", "%p" ]

[language-server.texlab.config.texlab.chktex]
onOpenAndSave = true

# introduce new language server
[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 20     # set max completion results len for each group: words, snippets, unicode-input
snippets_first = true         # completions will return before snippets by default
feature_words = true          # enable completion by word
feature_snippets = true       # enable snippets
feature_unicode_input = true  # enable "unicode input"
feature_paths = true          # enable path completion

# write logs to /tmp/completion.log
[language-server.scls.environment]
RUST_LOG = "info,simple-completion-langauge-server=info"
LOG_FILE = "/tmp/completion.log"

# append langage server to existed languages
[[language]]
name = "rust"
language-servers = [ "scls", "rust-analyzer" ]

[[language]]
name = "latex"
language-servers = [ "scls", "texlab" ]

[[language]]
name = "markdown"
language-servers = [ "scls", "marksman", "markdown-oxide" ]

[[language]]
name = "java"
language-servers = [ "scls", "jdtls" ]

[[language]]
name = "python"
language-servers = [ "scls", "pylsp" ]

[[language]]
name = "cpp"
language-servers = [ "scls", "clangd" ]

[[language]]
name = "c"
language-servers = [ "scls", "clangd" ]

[[language]]
name = "html"
language-servers = [ "scls", "vscode-html-language-server" ]
`

and my external-snippets.toml
`[[sources]] # list of sources to load
name = "friendly-snippets"  # optional name shown on snippet description
git = "https://github.com/rafamadriz/friendly-snippets.git" # git repo with snippets collections

[[sources.paths]]
scope = ["python"]
path = "snippets/python/base.json"

[[sources.paths]]
scope = ["python"]
path = "snippets/python/comprehension.json"

[[sources.paths]]
scope = ["python"]
path = "snippets/python/debug.json"

[[sources.paths]]
scope = ["python"]
path = "snippets/python/pydoc.json"

[[sources.paths]]
scope = ["python"]
path = "snippets/python/python.json"

[[sources.paths]]
scope = ["python"]
path = "snippets/python/unittest.json"

[[sources.paths]]
scope = ["rust"]
path = "snippets/rust/rust.json"

[[sources.paths]]
scope = ["rust"]
path = "snippets/rust/rustdoc.json"

[[sources.paths]]
scope = ["html"]
path = "snippets/html.json"

[[sources.paths]]
scope = ["latex"]
path = "snippets/latex.json"

[[sources.paths]]
scope = ["latex"]
path = "snippets/latex/latex-snippets.json"

[[sources.paths]]
scope = ["latex"]
path = "snippets/latex/bibtex.json"

[[sources.paths]]
scope = ["latex"]
path = "snippets/latex/vscode-latex-snippets.json"

[[sources.paths]]
scope = ["markdown"]
path = "snippets/markdown.json"

[[sources.paths]]
scope = ["java"]
path = "snippets/java/java-tests.json"

[[sources.paths]]
scope = ["java"]
path = "snippets/java/java.json"

[[sources.paths]]
scope = ["java"]
path = "snippets/java/javadoc.json"

[[sources.paths]]
scope = ["cpp"]
path = "snippets/cpp/cpp.json"

[[sources.paths]]
scope = ["cpp"]
path = "snippets/cpp/cppdoc.json"

[[sources.paths]]
scope = ["c"]
path = "snippets/c/c.json"

[[sources.paths]]
scope = ["c"]
path = "snippets/c/cdoc.json"
`

i ran 
simple-completion-language-server fetch-external-snippets
and it is up to date

but when i do 
simple-completion-language-server validate-snippets
`2024-03-23T23:40:15.112075Z  INFO simple_completion_language_server::snippets::config: Try read config from: "/home/sg/.config/helix/external-snippets.toml"
2024-03-23T23:40:15.112355Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/sg/.config/helix/external-snippets/github.com/rafamadriz/friendly-snippets.git/snippets/python/base.json" for scope: Some(["python"])
2024-03-23T23:40:15.112557Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/sg/.config/helix/external-snippets/github.com/rafamadriz/friendly-snippets.git/snippets/python/comprehension.json" for scope: Some(["python"])
2024-03-23T23:40:15.112616Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/sg/.config/helix/external-snippets/github.com/rafamadriz/friendly-snippets.git/snippets/python/debug.json" for scope: Some(["python"])
2024-03-23T23:40:15.112673Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/sg/.config/helix/external-snippets/github.com/rafamadriz/friendly-snippets.git/snippets/python/pydoc.json" for scope: Some(["python"])
2024-03-23T23:40:15.112789Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/sg/.config/helix/external-snippets/github.com/rafamadriz/friendly-snippets.git/snippets/python/python.json" for scope: Some(["python"])
2024-03-23T23:40:15.112900Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/sg/.config/helix/external-snippets/github.com/rafamadriz/friendly-snippets.git/snippets/python/unittest.json" for scope: Some(["python"])
2024-03-23T23:40:15.112961Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/sg/.config/helix/external-snippets/github.com/rafamadriz/friendly-snippets.git/snippets/rust/rust.json" for scope: Some(["rust"])
2024-03-23T23:40:15.113301Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/sg/.config/helix/external-snippets/github.com/rafamadriz/friendly-snippets.git/snippets/rust/rustdoc.json" for scope: Some(["rust"])
2024-03-23T23:40:15.113468Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/sg/.config/helix/external-snippets/github.com/rafamadriz/friendly-snippets.git/snippets/html.json" for scope: Some(["html"])
2024-03-23T23:40:15.114083Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/sg/.config/helix/external-snippets/github.com/rafamadriz/friendly-snippets.git/snippets/latex.json" for scope: Some(["latex"])
thread 'main' panicked at src/main.rs:170:55:
Failed to validate snippets: missing field `prefix` at line 557 column 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

RUST_BACKTRACE=full simple-completion-language-server validate-snippets
`2024-03-23T23:40:52.276220Z  INFO simple_completion_language_server::snippets::config: Try read config from: "/home/sg/.config/helix/external-snippets.toml"
2024-03-23T23:40:52.276523Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/sg/.config/helix/external-snippets/github.com/rafamadriz/friendly-snippets.git/snippets/python/base.json" for scope: Some(["python"])
2024-03-23T23:40:52.276739Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/sg/.config/helix/external-snippets/github.com/rafamadriz/friendly-snippets.git/snippets/python/comprehension.json" for scope: Some(["python"])
2024-03-23T23:40:52.276810Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/sg/.config/helix/external-snippets/github.com/rafamadriz/friendly-snippets.git/snippets/python/debug.json" for scope: Some(["python"])
2024-03-23T23:40:52.276877Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/sg/.config/helix/external-snippets/github.com/rafamadriz/friendly-snippets.git/snippets/python/pydoc.json" for scope: Some(["python"])
2024-03-23T23:40:52.277005Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/sg/.config/helix/external-snippets/github.com/rafamadriz/friendly-snippets.git/snippets/python/python.json" for scope: Some(["python"])
2024-03-23T23:40:52.277129Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/sg/.config/helix/external-snippets/github.com/rafamadriz/friendly-snippets.git/snippets/python/unittest.json" for scope: Some(["python"])
2024-03-23T23:40:52.277201Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/sg/.config/helix/external-snippets/github.com/rafamadriz/friendly-snippets.git/snippets/rust/rust.json" for scope: Some(["rust"])
2024-03-23T23:40:52.277433Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/sg/.config/helix/external-snippets/github.com/rafamadriz/friendly-snippets.git/snippets/rust/rustdoc.json" for scope: Some(["rust"])
2024-03-23T23:40:52.277497Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/sg/.config/helix/external-snippets/github.com/rafamadriz/friendly-snippets.git/snippets/html.json" for scope: Some(["html"])
2024-03-23T23:40:52.277716Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/sg/.config/helix/external-snippets/github.com/rafamadriz/friendly-snippets.git/snippets/latex.json" for scope: Some(["latex"])
thread 'main' panicked at src/main.rs:170:55:
Failed to validate snippets: missing field `prefix` at line 557 column 1

Stack backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   1: simple_completion_language_server::snippets::config::load_snippets_from_file
   2: simple_completion_language_server::snippets::config::load_snippets_from_path
   3: simple_completion_language_server::snippets::config::load_snippets
   4: simple_completion_language_server::validate_snippets
   5: simple_completion_language_server::main::{{closure}}
   6: tokio::runtime::park::CachedParkThread::block_on
   7: tokio::runtime::context::runtime::enter_runtime
   8: tokio::runtime::runtime::Runtime::block_on
   9: simple_completion_language_server::main
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: std::rt::lang_start::{{closure}}
  12: std::rt::lang_start_internal
  13: main
  14: <unknown>
  15: __libc_start_main
  16: _start
stack backtrace:
   0:     0x597d5c445036 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::haf2d35df03bb82cd
   1:     0x597d5c471be0 - core::fmt::write::h371936a176bfbef5
   2:     0x597d5c44205d - std::io::Write::write_fmt::h0994ff426a8c4f9d
   3:     0x597d5c444e14 - std::sys_common::backtrace::print::h236573354cc25698
   4:     0x597d5c446ec7 - std::panicking::default_hook::{{closure}}::h6dda82d98808060e
   5:     0x597d5c446c29 - std::panicking::default_hook::h9c84f0ee43c3937d
   6:     0x597d5c447358 - std::panicking::rust_panic_with_hook::heb1de10d361fcc68
   7:     0x597d5c447232 - std::panicking::begin_panic_handler::{{closure}}::hf2c775df9ed7de74
   8:     0x597d5c445536 - std::sys_common::backtrace::__rust_end_short_backtrace::h06fcbb4b91cdae50
   9:     0x597d5c446f84 - rust_begin_unwind
  10:     0x597d5c07d8f5 - core::panicking::panic_fmt::h670a5221067c77d7
  11:     0x597d5c07de43 - core::result::unwrap_failed::hd1766e4632d3cc5a
  12:     0x597d5c1c8363 - core::result::Result<T,E>::expect::h70fe9dc503f0b350
  13:     0x597d5c1d1f31 - simple_completion_language_server::main::{{closure}}::h20437de30a41bdbf
  14:     0x597d5c1c8629 - tokio::runtime::park::CachedParkThread::block_on::hb83c4997ab807c58
  15:     0x597d5c21b8aa - tokio::runtime::context::runtime::enter_runtime::hd577e9ebb1f75608
  16:     0x597d5c227d9e - tokio::runtime::runtime::Runtime::block_on::hfe3e7f6835d0f0d8
  17:     0x597d5c1cfb90 - simple_completion_language_server::main::hf903e947418bb085
  18:     0x597d5c15c1e3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h39db11cc87166ae1
  19:     0x597d5c216979 - std::rt::lang_start::{{closure}}::h466a2f9214230c0d
  20:     0x597d5c439a01 - std::rt::lang_start_internal::he4526b20fe7498a0
  21:     0x597d5c1d29e5 - main
  22:     0x717cec4a4cd0 - <unknown>
  23:     0x717cec4a4d8a - __libc_start_main
  24:     0x597d5c07e145 - _start
  25:                0x0 - <unknown>`

**Comment by sga11** [comment]
thank you, it is working great (and BLAZINGLY FAST)

a small typo on in help section (feth -> fetch)

simple-completion-language-server feth-external-snippets
    Fetch external snippets (git clone or git pull).
simple-completion-language-server validate-snippets
    Read all snippets to ensure correctness.
simple-completion-language-server
    Start language server protocol on stdin+stdout.
